
package inventory_system;

import static inventory_system.MainWindow.exportButton;
import static inventory_system.MainWindow.previousButton;
import static inventory_system.MainWindow.nextButton;
import static inventory_system.MainWindow.saveButton;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tebogo kekana - kinotech (Pty) Ltd.
 */
public class CustomerList extends javax.swing.JInternalFrame {
    
    private static int id;
    private static int role;
    Date logtime;
    private Vector<Vector<String>> data; 
    private Vector<String> header;
    private static ArrayList<Category> listCategories;
    MyTableModel tmodel;
    public static int []  tableRowSelected;
    DB db;
    MainWindow main;
    
    public CustomerList()  {   
        
        logtime = new Date();
        initComponents();
        setCustomerList();
        //setTableData(true);
        customertable.addMouseListener(new CustomerList.MyMouseListener());
        customertable.setModel(tmodel); 
        customertable.createDefaultColumnsFromModel();
        this.getContentPane().setBackground(Color.white);
    }
   
    public class MyMouseListener extends MouseAdapter {
     public MyMouseListener() 
      {
      
      }
     
     public void mousePressed(MouseEvent e){
         if ((e.getClickCount() == 1) && (!e.isMetaDown()))
           {
             tableRowSelected = CustomerList.this.customertable.getSelectedRows();
           }
       }
  } 
    
    private void setCustomerList(){
       //Get Customers
        try
        {
          db = new DB(RunProgram.CONNECTION_MODE);
          data  = db.getCustomers();
          listCategories = db.getCategories();
          db.close();
        }
        catch (Exception e){ e.printStackTrace(); }
        
        tmodel = new MyTableModel();
        
        
        if(data.size() > 0){
          for(int x =0;x<data.size();x++){
            boolean status;
            if(Integer.parseInt(data.get(x).get(8)) == 1){
                status = true;
            }else{ status = false; }
            String name    = data.get(x).get(1);
            String city    = data.get(x).get(2);
            int catid      = Integer.parseInt(data.get(x).get(3));
            String cat     = getCategoryByID(catid);
            String conname = data.get(x).get(4);
            String email   = data.get(x).get(5);
            String tel     = data.get(x).get(6);
            String mobile  = data.get(x).get(7);
            tmodel.addRow( new Object[] { name, city, cat, conname, email, tel, mobile, status} );
          }
        }
        
        //Activate table on main screen
        MainWindow.setActiveTable(customertable);
        
    }
    
    private String getCategoryByID(int catid){
        String category = "";
        for(int x = 0;x<listCategories.size();x++){
            if(listCategories.get(x).getCatid() == catid){
                category = listCategories.get(x).getCatname();
            }
        }
        
        return category;
    }
    
    /*private void setTableData(boolean editable){
           int records = 0;
           if(editable){
            tmodel = new javax.swing.table.DefaultTableModel(data,header){
             @Override
             public boolean isCellEditable(int row, int column) {
             //all cells false
             return true;
              }
            };
            customertable.setModel(tmodel);
            records = tmodel.getRowCount();
            //file_dir.setText(""+records+" record(s) returned"); 
            //file_dir.setForeground(new Color(57,104,156)); 
            
           }else{
               tmodel = new javax.swing.table.DefaultTableModel(data,header){
             @Override
             public boolean isCellEditable(int row, int column) {
             //all cells false
             return false;
              }
            };
            customertable.setBackground(new Color(200,200,200)); 
            customertable.setModel(tmodel);  
            records = tmodel.getRowCount();
            //file_dir.setText(""+records+" record(s) returned"); 
            //file_dir.setForeground(new Color(57,104,156)); 
          }   
    }*/
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action_popupmenu = new javax.swing.JPopupMenu();
        edit_customer_menu = new javax.swing.JMenuItem();
        delete_customer_menu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        view_customer_quotes = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        add_quote_customer_menu = new javax.swing.JMenuItem();
        add_invoice_customer_menu = new javax.swing.JMenuItem();
        add_receipt_customer_menu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        quick_report_customer_menu = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        addCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        customertable = new javax.swing.JTable();

        edit_customer_menu.setText("Edit");
        edit_customer_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_customer_menuActionPerformed(evt);
            }
        });
        action_popupmenu.add(edit_customer_menu);

        delete_customer_menu.setText("Delete");
        action_popupmenu.add(delete_customer_menu);
        action_popupmenu.add(jSeparator2);

        view_customer_quotes.setText("View Quotes");
        view_customer_quotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_customer_quotesActionPerformed(evt);
            }
        });
        action_popupmenu.add(view_customer_quotes);
        action_popupmenu.add(jSeparator4);

        add_quote_customer_menu.setText("Add Quote");
        add_quote_customer_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_quote_customer_menuActionPerformed(evt);
            }
        });
        action_popupmenu.add(add_quote_customer_menu);

        add_invoice_customer_menu.setText("Add Invoice");
        action_popupmenu.add(add_invoice_customer_menu);

        add_receipt_customer_menu.setText("Add Receipt");
        action_popupmenu.add(add_receipt_customer_menu);
        action_popupmenu.add(jSeparator3);

        quick_report_customer_menu.setText("Quick Report");
        action_popupmenu.add(quick_report_customer_menu);

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEtchedBorder()));
        setTitle("Customer List");
        setPreferredSize(MainWindow.home_desktop.getPreferredSize());

        jLabel1.setText("List of Customers");

        addCustomer.setText("Add New Customer");
        addCustomer.setToolTipText("Add a new customer");
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });

        customertable.setModel(new javax.swing.table.DefaultTableModel(data,header));
        customertable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        customertable.setComponentPopupMenu(action_popupmenu);
        jScrollPane1.setViewportView(customertable);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCustomer, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        this.dispose();
        MainWindow.customerInternalFrame();
        MainWindow.customer.customer_title.setText("New Customer"); 
        MainWindow.customer.setMode(0); //edit mode, very important. 
        MainWindow.customer.setNewCustomerCode();
        exportButton.setEnabled(false); 
        previousButton.setEnabled(true);
        nextButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_addCustomerActionPerformed

    private void edit_customer_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_customer_menuActionPerformed
        int row = CustomerList.this.customertable.getSelectedRow();
        Object selectedvalue = CustomerList.this.customertable.getValueAt(row,0);
        String customername = (String) selectedvalue;
        int customerid      = getCustomerID(customername);
                
        this.dispose(); 
        MainWindow.customerInternalFrame();
        /*Customers customers = new Customers();
        customers.setVisible(true);
        customers.setSize(MainWindow.home_desktop.getWidth(), MainWindow.home_desktop.getHeight()); 
        ((BasicInternalFrameUI)customers.getUI()).setNorthPane(null);
        MainWindow.home_desktop.add(customers);
        try {
             customers.setSelected(true); 
            }
        catch (PropertyVetoException e) {e.printStackTrace(); }*/
        
        MainWindow.customer.customer_title.setText("Edit Customer - "+customername); 
        MainWindow.customer.setMode(1); //edit mode, very important. 
        MainWindow.customer.setCustomer(customerid);   
        exportButton.setEnabled(false); 
        previousButton.setEnabled(true);
        nextButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_edit_customer_menuActionPerformed

    private void add_quote_customer_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_quote_customer_menuActionPerformed
        // Add customer quotation
        int row = CustomerList.this.customertable.getSelectedRow();
        Object selectedvalue = CustomerList.this.customertable.getValueAt(row,0);
        String customername = (String) selectedvalue;
        int customerid      = getCustomerID(customername);
        this.dispose(); 
        MainWindow.customerInternalFrame();        
        MainWindow.customer.customer_title.setText("Edit Customer - "+customername); 
        MainWindow.customer.setMode(1); //edit mode, very important. 
        MainWindow.customer.setCustomer(customerid);         
        exportButton.setEnabled(false); 
        previousButton.setEnabled(true);
        nextButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_add_quote_customer_menuActionPerformed

    private void view_customer_quotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_customer_quotesActionPerformed
       //View Customer quotations
        int row = CustomerList.this.customertable.getSelectedRow();
        Object selectedvalue = CustomerList.this.customertable.getValueAt(row,0);
        String customername = (String) selectedvalue;
        int customerid      = getCustomerID(customername);
        this.dispose(); 
        MainWindow.customerQuotationsListInternalFrame();        
        MainWindow.quotationsList.quote_title.setText("Customer Quotes - "+customername); 
        MainWindow.quotationsList.setCustomerQuoteList(customerid);      
        exportButton.setEnabled(false); 
        previousButton.setEnabled(true);
        nextButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_view_customer_quotesActionPerformed
    
    private int getCustomerID(String customername){
        int id = 0;
        for(int x = 0;x< data.size();x++){
            if(data.get(x).elementAt(1) == customername){
                id = Integer.parseInt(data.get(x).elementAt(0));
            }
        }
        
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu action_popupmenu;
    private javax.swing.JButton addCustomer;
    private javax.swing.JMenuItem add_invoice_customer_menu;
    private javax.swing.JMenuItem add_quote_customer_menu;
    private javax.swing.JMenuItem add_receipt_customer_menu;
    private javax.swing.JTable customertable;
    private javax.swing.JMenuItem delete_customer_menu;
    private javax.swing.JMenuItem edit_customer_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem quick_report_customer_menu;
    private javax.swing.JMenuItem view_customer_quotes;
    // End of variables declaration//GEN-END:variables

    public class MyTableModel extends DefaultTableModel {

    public MyTableModel() {
      super(new String[]{"Name", "City", "Category","Contact Name", "E-Mail", "Tel No.", "Mobile No.", "Active"}, 0);
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) {
      Class clazz = String.class;
      switch (columnIndex) {
        case 0:
          clazz = String.class;
          break;
        case 7:
          clazz = Boolean.class;
          break;
      }
      return clazz;
    }

    @Override
    public boolean isCellEditable(int row, int column) {
      return false;
    }

    @Override
    public void setValueAt(Object aValue, int row, int column) {
      if (aValue instanceof Boolean && column == 2) {
        System.out.println(aValue);
        Vector rowData = (Vector)getDataVector().get(row);
        rowData.set(2, (boolean)aValue);
        fireTableCellUpdated(row, column);
      }
      else{
          Vector rowData = (Vector)getDataVector().get(row);
          rowData.set(column, aValue);
          fireTableCellUpdated(row, column);
         
      }
    }

  }
    
    private boolean hasSpace(String table_field)     { 
       boolean answer; 
       if(table_field.contains(" ")){ 
           answer = true;
       }else{
         answer =false;
    }
     return answer;  
   }
}
