/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_system;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qxf3984
 */
public class IssueListGUI extends javax.swing.JInternalFrame {
    
    private static int id;
    private static int role;
    Date logtime;
    public static int []  rowSelected;
    private Vector<Vector<String>> data; 
    private Vector<String> header;
    private Object ID;
    private DefaultTableModel model;   
    
    
    public IssueListGUI(int idin, int roleIn){
        id      = idin;
        role    = roleIn;
        logtime = new Date();
        model = new javax.swing.table.DefaultTableModel(data,header);
        //create headers for search table
        header = new Vector<String>();
        header.add("Issue ID");
        header.add("ID");
        header.add("Store");
        header.add("Location / Bin");
        header.add("Description");
        header.add("Quantity");
        header.add("Date");
        header.add("Learner");
        header.add("Company ID");
        header.add("Group");
        header.add("Level");
        header.add("Facilitator");
        header.add("Storeman");
        
        initComponents();

        this.getContentPane().setBackground(Color.white);  //sets layout background color to white
        
        try
        {
          ConnectDatabase database = new ConnectDatabase();
          data  = database.setIssueListTable("issue_list_01");
          database.setCloseDatabase();
        }
        catch (Exception e_exception)
        {
          e_exception.printStackTrace();
        }
        
        //populate the tables with data
        issueListTable.setModel(new javax.swing.table.DefaultTableModel(data,header)); 
          
        //Activate table on main screen
        MainWindow.setActiveTable(issueListTable);
    }

    private IssueListGUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBox_store = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        textfield_location = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueListTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textfield_description = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Issued Items");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Store");

        comboBox_store.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Tool store", "Consumable store", "Equipment store" }));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Location");

        issueListTable.setModel(new javax.swing.table.DefaultTableModel(data,header));
        jScrollPane1.setViewportView(issueListTable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Issued Items ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(624, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        textfield_description.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        textfield_description.setForeground(new java.awt.Color(153, 153, 153));
        textfield_description.setText("Search Item...");
        textfield_description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfield_descriptionMouseClicked(evt);
            }
        });
        textfield_description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfield_descriptionKeyTyped(evt);
            }
        });

        searchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_system/image/search2.png"))); // NOI18N
        searchButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory_system/image/search.png"))); // NOI18N
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBox_store, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_location, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(textfield_description, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBox_store, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(textfield_location, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfield_description, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_descriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfield_descriptionMouseClicked
        textfield_description.setText("");
    }//GEN-LAST:event_textfield_descriptionMouseClicked

    private void textfield_descriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_descriptionKeyTyped
        textfield_description.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textfield_description.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_textfield_descriptionKeyTyped

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // Search

        String comboBox_store_item = (String)comboBox_store.getSelectedItem();
        String textfield_location_item = textfield_location.getText();
        if (textfield_location_item.equals(""))
        {
            textfield_location_item = "%";
        }

        String textfield_description_item = textfield_description.getText();
        if(textfield_description_item.equals("Search Item...")){
            textfield_description_item = "";
        }
        String sgl_string = "";

        try
        {
            ConnectDatabase database = new ConnectDatabase();

            if (!comboBox_store_item.equals("All"))
            {
                sgl_string = sgl_string + " Store like '%" + comboBox_store_item + "%'";
            }
            if (!textfield_location_item.equals(""))
            {
                if (!sgl_string.equals("")) {
                    sgl_string = sgl_string + " AND";
                }
                sgl_string = sgl_string + " `Location / Bin` like '" + textfield_location_item + "'";
            }

            if (!textfield_description_item.equals(""))
            {
                if (!sgl_string.equals("")) {
                    sgl_string = sgl_string + " AND";
                }
                sgl_string = sgl_string + " Description like '%" + textfield_description_item + "%'";
            }

            data = database.setIssueListTableSearch(sgl_string,"issue_list_01");
            database.setCloseDatabase();
        }
        catch (Exception e_exception)
        {
            e_exception.printStackTrace();
        }

        issueListTable.setModel(new javax.swing.table.DefaultTableModel(data,header));
    }//GEN-LAST:event_searchButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueListGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox_store;
    private javax.swing.JTable issueListTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField textfield_description;
    private javax.swing.JTextField textfield_location;
    // End of variables declaration//GEN-END:variables
}
