package inventory_system;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qxf3984
 */

public class PendingItems extends JInternalFrame 
{
    Date logtime;
    public static int []  rowSelected;
    protected Vector<Vector<String>> data; 
    private Vector<String> header;
    private Object ID;
    private DefaultTableModel model;
    private String test;
    public String email;
    private javax.swing.JLabel description_lb;
    private javax.swing.JLabel email_lb;
    private javax.swing.JLabel facilitator_lb;
    private javax.swing.JLabel group_level_lb;
    private javax.swing.JLabel image_lb;
    private javax.swing.JLabel issued_out_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel name_surname_lb;
    private java.awt.Panel main;
    private java.awt.Panel panel2;
    private javax.swing.JTable pendingItemsTable;
    private javax.swing.JLabel qty_lb;
    private javax.swing.JLabel storeman_lb;
    
    public PendingItems() 
    {   
        logtime = new Date(); 
        model = new javax.swing.table.DefaultTableModel(data,header);
       
        //create headers for consumable table
        header = new Vector<String>();
        header.add("Issue ID");
        header.add("Name");
        header.add("Company ID");
        header.add("Item No.");
        header.add("Item Descrip.");
        header.add("Quantity");
        header.add("Date Issued");
        header.add("Location");
        header.add("Facilitator");
        header.add("Storeman");
       
       initComponents();
       
       this.getContentPane().setBackground(Color.white);
       
        try
        {
          ConnectDatabase database = new ConnectDatabase();
          data  = database.setPendingItemsTable();
          database.setCloseDatabase();
        }
        catch (Exception e_exception)
        {
          e_exception.printStackTrace();
        }
        
       pendingItemsTable.setModel(new javax.swing.table.DefaultTableModel(data,header)); 
       
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingItemsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        issued_out_lb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        description_lb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qty_lb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        storeman_lb = new javax.swing.JLabel();
        name_surname_lb = new javax.swing.JLabel();
        main = new java.awt.Panel();
        image_lb = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        facilitator_lb = new javax.swing.JLabel();
        group_level_lb = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email_lb = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(835, 602); //setSize(835, 590) or setSize(714, 475); (horizontal, vertical)
        setLocation(0, 0);

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label1.setText("Displays learners with pending Items to be received");

        pendingItemsTable.setModel(new javax.swing.table.DefaultTableModel(data,header));
        pendingItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pendingItemsTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(pendingItemsTable);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setText("Date Issued out");

        issued_out_lb.setBackground(new java.awt.Color(255, 255, 255));
        issued_out_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        issued_out_lb.setForeground(new java.awt.Color(135, 85, 85));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Description");

        description_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        description_lb.setForeground(new java.awt.Color(135, 85, 85));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Quantity");

        qty_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        qty_lb.setForeground(new java.awt.Color(135, 85, 85));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Storeman");

        storeman_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        storeman_lb.setForeground(new java.awt.Color(135, 85, 85));

        name_surname_lb.setBackground(new java.awt.Color(255, 255, 255));
        name_surname_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        name_surname_lb.setForeground(new java.awt.Color(135, 85, 85));

        image_lb.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("Facilitator");

        facilitator_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        facilitator_lb.setForeground(new java.awt.Color(135, 85, 85));

        group_level_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        group_level_lb.setForeground(new java.awt.Color(135, 85, 85));

        panel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel8.setText("Issued Item");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setText("Issued To:");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        email_lb.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        email_lb.setForeground(new java.awt.Color(0, 0, 255));
        email_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                email_lbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                email_lbMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                email_lbMousePressed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(0, Short.MAX_VALUE)   //.addContainerGap(275, Short.MAX_VALUE) //take note of this
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qty_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(description_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(issued_out_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(facilitator_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(storeman_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(40, 40, 40)
                        //.addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27) //-1, 619, 32767
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_surname_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(group_level_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email_lb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addContainerGap(300,javax.swing.GroupLayout.PREFERRED_SIZE)) //this fills the entire window horizontally
                       //.addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(issued_out_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(description_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qty_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(storeman_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name_surname_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(group_level_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facilitator_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE)  //##NOTE## Vertical size of main is set here
                )
        );

        pack();
    }// </editor-fold>                        

    private void pendingItemsTableMousePressed(java.awt.event.MouseEvent evt) {                                               
        
         // single click on the a row and display learner and item info below the table
       if ((evt.getClickCount() == 1) && (!evt.isMetaDown()))
        { //get values from the row selected
          int row = PendingItems.this.pendingItemsTable.getSelectedRow();
          String thisID = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 0);
          String name   = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 1);
          String compid = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 2);
          int companyid = Integer.parseInt(compid);
          String itemNo = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 3);
          String itemDescrip   = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 4);
          String qty   = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 5);
          String dateIssued   = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 6);
          String location   = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 7);
          String faci   = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 8);
          String storeman   = (String) PendingItems.this.pendingItemsTable.getValueAt(row, 9);
          String surname = "";
          String group = "";
          int level = 0;
          
          //get image of learner selected
          ImageIcon icon = null;  
          try{ icon = new ImageIcon(new java.net.URL("http://haf0gau01.w9/photos/"+companyid+".jpg"));}
          catch (MalformedURLException ex){Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);}
          
          //get learner small detail
            try{ ConnectDatabase database = new ConnectDatabase();
                  surname = database.getString("SELECT `surname` FROM learner_list WHERE `company_id` LIKE '" + companyid + "'");
                  group = database.getString("SELECT `group` FROM learner_list WHERE `company_id` LIKE '" + companyid + "'");
                  level = Integer.parseInt(database.getString("SELECT `level` FROM learner_list WHERE `company_id` LIKE '" + companyid + "'"));
                  email = database.getString("SELECT `e_mail` FROM learner_list WHERE `company_id` LIKE '" + companyid + "'");
                  database.setCloseDatabase();
                }
            catch (Exception e1){e1.printStackTrace();}
            
          //Resize the image icon   
          java.awt.Image img = icon.getImage();
          BufferedImage bi = new BufferedImage(125,125,BufferedImage.TYPE_INT_RGB);
          bi.getGraphics().drawImage(img, 0, 0, null);
          Graphics g = bi.getGraphics();
          g.drawImage(img,0,0, 125, 125,this);
          ImageIcon newIcon = new ImageIcon(bi);
          
          //now assign selected values to the UI
          name_surname_lb.setText(name+" "+surname);
          issued_out_lb.setText(dateIssued); 
          description_lb.setText(itemDescrip);  
          qty_lb.setText(qty); 
          storeman_lb.setText(storeman); 
          facilitator_lb.setText(faci); 
          image_lb.setIcon(newIcon); 
          group_level_lb.setText(group+" "+level);
          //email_lb.setText("<html><font color=\"#000099\"><u>"+email+"</u></font></html>");
          email_lb.setText("<html><u>"+email+"</u></html>");
          email_lb.setToolTipText("E-mail: "+email); 
          
          
        }

       
    }                                              

    private void email_lbMousePressed(java.awt.event.MouseEvent evt) {                                      
        
        //MailBoxWindow box = new MailBoxWindow(email);
        MailBoxWindow box = new MailBoxWindow("invt_store_program@bmw.co.za");
        box.setVisible(true);
    }                                     

    private void email_lbMouseExited(java.awt.event.MouseEvent evt) {                                     
        //email_lb.setForeground(new Color(135,85,85));
        email_lb.setForeground(Color.blue);
        email_lb.setFont(new Font("SansSerif",Font.BOLD,12));
    }                                    

    private void email_lbMouseEntered(java.awt.event.MouseEvent evt) {                                      
       //email_lb.setOpaque(false);
        email_lb.setForeground(Color.blue);
        email_lb.setFont(new Font("SansSerif",Font.BOLD,13)); 
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingItems().setVisible(true);
            }
        });
    }
                 
}
