
package inventory_system;

import static inventory_system.MainWindow.exportButton;
import static inventory_system.MainWindow.previousButton;
import static inventory_system.MainWindow.nextButton;
import static inventory_system.MainWindow.saveButton;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tebogo kekana - kinotech (Pty) Ltd.
 */
public class QuotationList extends javax.swing.JInternalFrame {
    
    private static int id;
    private static int role;
    Date logtime;
    private Vector<Vector<String>> data; 
    private Vector<String> header;
    //private static ArrayList<Category> listCategories;
    MyTableModel tmodel;
    public static int []  tableRowSelected;
    DB db;
    MainWindow main;
    
    public QuotationList()  {   
        
        logtime = new Date();
        initComponents();
        //setCustomerQuoteList();
        //setTableData(true);
        //quotestable.addMouseListener(new QuotationList.MyMouseListener());
        //quotestable.setModel(tmodel); 
        //quotestable.createDefaultColumnsFromModel();
        this.getContentPane().setBackground(Color.white);
    }
   
    public class MyMouseListener extends MouseAdapter {
     public MyMouseListener() 
      {
      
      }
     
     public void mousePressed(MouseEvent e){
         if ((e.getClickCount() == 1) && (!e.isMetaDown()))
           {
             tableRowSelected = QuotationList.this.quotestable.getSelectedRows();
           }
       }
  } 
    
    protected void setQuotationList(){
       //Get quotations list of all customers
        try
        {
          db = new DB(RunProgram.CONNECTION_MODE);
          data  = db.getQuotations();
          db.close();
        }
        catch (Exception e){ e.printStackTrace(); }
        
        tmodel = new MyTableModel();
        
        
        if(data.size() > 0){
          for(int x =0;x<data.size();x++){
            boolean status = false;
            /*if(Integer.parseInt(data.get(x).get(6)) == 1){
                status = true;
            }*/
            String quote   = data.get(x).get(0);
            String name    = data.get(x).get(1);
            String qstatus    = data.get(x).get(2);
            String total = data.get(x).get(3);
            String cdate   = data.get(x).get(4);
            String edate     = data.get(x).get(5);
            tmodel.addRow( new Object[] { quote, name, qstatus,total, cdate, edate, status} );
          }
        }
        
        quotestable.addMouseListener(new QuotationList.MyMouseListener());
        quotestable.setModel(tmodel); 
        quotestable.createDefaultColumnsFromModel();
        //Activate table on main screen
        MainWindow.setActiveTable(quotestable);
        
    }
    
    protected void setCustomerQuoteList(int customerid){
       //Get quotations list of a single customer
        try
        {
          db = new DB(RunProgram.CONNECTION_MODE);
          data  = db.getCustomerQuotations(customerid); 
          db.close();
        }
        catch (Exception e){ e.printStackTrace(); }
        
        tmodel = new MyTableModel();
        
        
        if(data.size() > 0){
          for(int x =0;x<data.size();x++){
            boolean status = false;
            /*if(Integer.parseInt(data.get(x).get(6)) == 1){
                status = true;
            }*/
            String quote   = data.get(x).get(0);
            String name    = data.get(x).get(1);
            String qstatus    = data.get(x).get(2);
            String total = data.get(x).get(3);
            String cdate   = data.get(x).get(4);
            String edate     = data.get(x).get(5);
            tmodel.addRow( new Object[] { quote, name, qstatus,total, cdate, edate, status} );
          }
        }
        
        quotestable.addMouseListener(new QuotationList.MyMouseListener());
        quotestable.setModel(tmodel); 
        quotestable.createDefaultColumnsFromModel();
        //Activate table on main screen
        MainWindow.setActiveTable(quotestable);
        
    } 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action_popupmenu = new javax.swing.JPopupMenu();
        edit_customer_menu = new javax.swing.JMenuItem();
        delete_customer_menu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        add_quote_customer_menu = new javax.swing.JMenuItem();
        add_invoice_customer_menu = new javax.swing.JMenuItem();
        add_receipt_customer_menu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        quick_report_customer_menu = new javax.swing.JMenuItem();
        quote_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        addQuote = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        quotestable = new javax.swing.JTable();

        edit_customer_menu.setText("Edit");
        edit_customer_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_customer_menuActionPerformed(evt);
            }
        });
        action_popupmenu.add(edit_customer_menu);

        delete_customer_menu.setText("Delete");
        action_popupmenu.add(delete_customer_menu);
        action_popupmenu.add(jSeparator2);

        add_quote_customer_menu.setText("Add Quote");
        add_quote_customer_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_quote_customer_menuActionPerformed(evt);
            }
        });
        action_popupmenu.add(add_quote_customer_menu);

        add_invoice_customer_menu.setText("Add Invoice");
        action_popupmenu.add(add_invoice_customer_menu);

        add_receipt_customer_menu.setText("Add Receipt");
        action_popupmenu.add(add_receipt_customer_menu);
        action_popupmenu.add(jSeparator3);

        quick_report_customer_menu.setText("Quick Report");
        action_popupmenu.add(quick_report_customer_menu);

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEtchedBorder()));
        setTitle("Customers Quotes");
        setPreferredSize(MainWindow.home_desktop.getPreferredSize());

        quote_title.setText("Customer's Quotes");

        addQuote.setText("Add Quotation");
        addQuote.setToolTipText("Add new quote");
        addQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuoteActionPerformed(evt);
            }
        });

        quotestable.setModel(new javax.swing.table.DefaultTableModel(data,header));
        quotestable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        quotestable.setComponentPopupMenu(action_popupmenu);
        jScrollPane1.setViewportView(quotestable);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addQuote)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(quote_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quote_title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addQuote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        quote_title.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuoteActionPerformed
        this.dispose();
        MainWindow.customerQuotationsInternalFrame();
        MainWindow.quotations.quotation_title.setText("New Customer Quote"); 
        MainWindow.quotations.setNewQuote();
        MainWindow.quotations.setQuoteStatus();
        exportButton.setEnabled(false); 
        previousButton.setEnabled(true);
        nextButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_addQuoteActionPerformed

    private void edit_customer_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_customer_menuActionPerformed
        int row = QuotationList.this.quotestable.getSelectedRow();
        Object selectedvalue = QuotationList.this.quotestable.getValueAt(row,0);
        String customername = (String) selectedvalue;
        int customerid      = getCustomerID(customername);
                
        this.dispose(); 
        MainWindow.customerInternalFrame();
        /*Customers customers = new Customers();
        customers.setVisible(true);
        customers.setSize(MainWindow.home_desktop.getWidth(), MainWindow.home_desktop.getHeight()); 
        ((BasicInternalFrameUI)customers.getUI()).setNorthPane(null);
        MainWindow.home_desktop.add(customers);
        try {
             customers.setSelected(true); 
            }
        catch (PropertyVetoException e) {e.printStackTrace(); }*/
        
        MainWindow.customer.customer_title.setText("Edit Customer - "+customername); 
        MainWindow.customer.setMode(1); //edit mode, very important. 
        MainWindow.customer.setCustomer(customerid);   
        exportButton.setEnabled(false); 
        previousButton.setEnabled(true);
        nextButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_edit_customer_menuActionPerformed

    private void add_quote_customer_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_quote_customer_menuActionPerformed
        // Add customer quotation
        int row = QuotationList.this.quotestable.getSelectedRow();
        Object selectedvalue = QuotationList.this.quotestable.getValueAt(row,0);
        String customername = (String) selectedvalue;
        int customerid      = getCustomerID(customername);
        this.dispose(); 
        MainWindow.customerInternalFrame();        
        MainWindow.customer.customer_title.setText("Edit Quote - "+customername); 
        MainWindow.customer.setMode(1); //edit mode, very important. 
        MainWindow.customer.setCustomer(customerid);         
        exportButton.setEnabled(false); 
        previousButton.setEnabled(true);
        nextButton.setEnabled(false);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_add_quote_customer_menuActionPerformed
    
    private int getCustomerID(String customername){
        int id = 0;
        for(int x = 0;x< data.size();x++){
            if(data.get(x).elementAt(1) == customername){
                id = Integer.parseInt(data.get(x).elementAt(0));
            }
        }
        
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu action_popupmenu;
    private javax.swing.JButton addQuote;
    private javax.swing.JMenuItem add_invoice_customer_menu;
    private javax.swing.JMenuItem add_quote_customer_menu;
    private javax.swing.JMenuItem add_receipt_customer_menu;
    private javax.swing.JMenuItem delete_customer_menu;
    private javax.swing.JMenuItem edit_customer_menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem quick_report_customer_menu;
    public static javax.swing.JLabel quote_title;
    private javax.swing.JTable quotestable;
    // End of variables declaration//GEN-END:variables

    public class MyTableModel extends DefaultTableModel {

    public MyTableModel() {
      super(new String[]{"Quote No.","Customer Name", "Status", "Total Price","Date Created","Expiry Date", "Mailed"}, 0);
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) {
      Class clazz = String.class;
      switch (columnIndex) {
        case 0:
          clazz = String.class;
          break;
        case 6:
          clazz = Boolean.class;
          break;
      }
      return clazz;
    }

    @Override
    public boolean isCellEditable(int row, int column) {
      return false;
    }

    @Override
    public void setValueAt(Object aValue, int row, int column) {
      if (aValue instanceof Boolean && column == 2) {
        System.out.println(aValue);
        Vector rowData = (Vector)getDataVector().get(row);
        rowData.set(2, (boolean)aValue);
        fireTableCellUpdated(row, column);
      }
      else{
          Vector rowData = (Vector)getDataVector().get(row);
          rowData.set(column, aValue);
          fireTableCellUpdated(row, column);
         
      }
    }

  }
    
    private boolean hasSpace(String table_field)     { 
       boolean answer; 
       if(table_field.contains(" ")){ 
           answer = true;
       }else{
         answer =false;
    }
     return answer;  
   }
}
